In [ ]:
!pip install tensorflow
!pip install tensorflow_hub
!pip install -q -U "tensorflow-text==2.13.*"
!pip install "tf-models-official==2.13.*"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 22.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 479.7/479.7 MB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 82.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 81.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 37.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 9.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.4/106.4 kB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 73.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 27.2 MB/s eta 0:00:00
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=5251fa8963609cda4c164c5a65ab0e8d44401d50d89883ececedc3b590237e28
  

In [ ]:
!pip install gdown

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf
import gdown
import tensorflow_hub as hub
import tensorflow_text as text
import tensorflow as tf
import os

In [ ]:
# unduh zip file
file_id = "1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX"
output_file = "/content/model_sn.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm"
output_file = "/content/model_tf.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0"
output_file = "/content/model_ei.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")

# unduh zip file
file_id = "1-6NNq0PKXmuxbKf4jVvn1EOmlD4oXzrT"
output_file = "/content/model_jp.zip"

gdown.download(f"https://drive.google.com/uc?id={file_id}", output_file)
if os.path.exists(output_file):
  print("File berhasil diunduh ke ", output_file)
else:
  print("file gagal diunduh")
# https://drive.google.com/file/d/1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX/view?usp=drive_link
# https://drive.google.com/file/d/1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm/view?usp=sharing
# https://drive.google.com/file/d/1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0/view?usp=sharing
# https://drive.google.com/file/d/1--fBI59iDhoW67XlevG8kH-vA-mb3lus/view?usp=sharing

Downloading...
From: https://drive.google.com/uc?id=1-jUsdSAEf5iUyR1ZGvvvRatE_vcETSjX
To: /content/model_sn.zip
100%|██████████| 666M/666M [00:07<00:00, 90.1MB/s]


File berhasil diunduh ke  /content/model_sn.zip


Downloading...
From: https://drive.google.com/uc?id=1am-Q1f2YNMgNhIj2jV2WIMjhs1jRU1Zm
To: /content/model_tf.zip
100%|██████████| 664M/664M [00:08<00:00, 79.1MB/s]


File berhasil diunduh ke  /content/model_tf.zip


Downloading...
From: https://drive.google.com/uc?id=1-OXvFKlgCUrU28IkBzzt1DAvMdVCY1T0
To: /content/model_ei.zip
100%|██████████| 665M/665M [00:08<00:00, 82.0MB/s]


File berhasil diunduh ke  /content/model_ei.zip


Downloading...
From: https://drive.google.com/uc?id=1-6NNq0PKXmuxbKf4jVvn1EOmlD4oXzrT
To: /content/model_jp.zip
100%|██████████| 1.31G/1.31G [00:09<00:00, 133MB/s]

File berhasil diunduh ke  /content/model_jp.zip


In [ ]:
!unzip /content/model_jp.zip -d /content/JP_model
!unzip /content/model_sn.zip -d /content/SN_model
!unzip /content/model_ei.zip -d /content/EI_model
!unzip /content/model_tf.zip -d /content/TF_model

Archive:  /content/model_jp.zip
  inflating: /content/JP_model/fingerprint.pb  
  inflating: /content/JP_model/saved_model.pb  
  inflating: /content/JP_model/keras_metadata.pb  
  inflating: /content/JP_model/variables/variables.index  
  inflating: /content/JP_model/variables/variables.data-00000-of-00001  
  inflating: /content/JP_model/assets/vocab.txt  
Archive:  /content/model_sn.zip
  inflating: /content/SN_model/fingerprint.pb  
  inflating: /content/SN_model/saved_model.pb  
  inflating: /content/SN_model/keras_metadata.pb  
  inflating: /content/SN_model/variables/variables.data-00000-of-00001  
  inflating: /content/SN_model/variables/variables.index  
  inflating: /content/SN_model/assets/vocab.txt  
Archive:  /content/model_ei.zip
   creating: /content/EI_model/content/drive/MyDrive/EI_model/
   creating: /content/EI_model/content/drive/MyDrive/EI_model/variables/
  inflating: /content/EI_model/content/drive/MyDrive/EI_model/variables/variables.data-00000-of-00001  
  infl

In [ ]:
model_ei = tf.keras.models.load_model("/content/EI_model/content/drive/MyDrive/EI_model")
model_sn = tf.keras.models.load_model("/content/SN_model")
model_tf = tf.keras.models.load_model("/content/TF_model")
model_jp = tf.keras.models.load_model("/content/JP_model")

In [ ]:
model_ei._name = 'model_ei'
model_sn._name = 'model_sn'
model_tf._name = 'model_tf'
model_jp._name = 'model_jp'
# model_sn.summary()
# model_tf.summary()

In [ ]:
# Load models
def build_classifier_model():
    text_input_ei = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_ei')
    text_input_sn = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_sn')
    text_input_tf = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_tf')
    text_input_jp = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text_input_jp')

    output_ei = model_ei(text_input_ei)
    output_sn = model_sn(text_input_sn)
    output_tf = model_tf(text_input_tf)
    output_jp = model_jp(text_input_jp)

    return tf.keras.Model([text_input_ei,text_input_sn,text_input_tf,text_input_jp], [output_ei,output_sn,output_tf,output_jp])

# Build and summarize the model
model = build_classifier_model()
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text_input_ei (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_sn (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_tf (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_jp (InputLayer)  [(None,)]                    0         []                            
                                                                                              

In [ ]:
import numpy as np
EI_text = np.array(['saya suka menyendiri'])
SN_text = np.array(['saya selalu mengikuti kata hati'])
TF_text = np.array(['saya sangat suka melakukakan analisis ketika memutuskan sesuatu'])
JP_text = np.array(['Jika jadwal padat menghampiri, saya lebih suka spontanitas dan fleksibilitas dalam menghadapinya'])
numpy_array = [EI_text,SN_text,TF_text,JP_text]
model.predict(numpy_array)

1/1 [==============================] - 3s 3s/step


[array([[0.11417162]], dtype=float32),
 array([[0.9435409]], dtype=float32),
 array([[0.00161317]], dtype=float32),
 array([[0.8607084]], dtype=float32)]

In [ ]:
model = build_classifier_model()
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 text_input_ei (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_sn (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_tf (InputLayer)  [(None,)]                    0         []                            
                                                                                                  
 text_input_jp (InputLayer)  [(None,)]                    0         []                            
                                                                                            

In [ ]:
model.save("/content/drive/MyDrive/Colab Notebooks/model_recommendation")