In [ ]:
!pip install tensorflow
!pip install transformers
!pip install pandas

In [ ]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForQuestionAnswering

model_name = 'cahya/bert-base-indonesian-522M'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForQuestionAnswering.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/62.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/230k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/468 [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/545M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForQuestionAnswering.

Some layers of TFBertForQuestionAnswering were not initialized from the model checkpoint at cahya/bert-base-indonesian-522M and are newly initialized: ['qa_outputs']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
import pandas as pd
import os

# Ganti 'nama_file.csv' dengan nama file CSV yang ingin Anda baca
file_path = '/content/chatbot dataset - Final Dataset.csv'

# Membaca file CSV menjadi DataFrame
df = pd.read_csv(file_path)

# Menampilkan beberapa baris pertama dari DataFrame
print(df.head())


                                                Text  \
0  Universitas Diponegoro, sering disingkat sebag...   
1  Universitas Diponegoro, sering disingkat sebag...   
2  Universitas Diponegoro, sering disingkat sebag...   
3  Universitas Diponegoro, sering disingkat sebag...   
4  Universitas Diponegoro, sering disingkat sebag...   

                                          Pertanyaan  \
0                     Apa itu universias diponegoro?   
1                           Apa yang dimaksud undip?   
2           Kapan Universitas Diponegoro didirikan ?   
3                            Kapan undip didirikan ?   
4  Dimana undip telah tumbuh menjadi institusi ya...   

                                             Jawaban  
0                sebuah universitas negeri terkemuka  
1                sebuah universitas negeri terkemuka  
2          Universitas ini didirikan pada tahun 1957  
3          Universitas ini didirikan pada tahun 1957  
4  universitas negeri terkemuka yang terletak di ..

In [ ]:
input_ids = tokenizer(list(df['Pertanyaan']),list(df['Text']), return_tensors='tf', padding=True, truncation=True)
print(input_ids['input_ids'].numpy(),list(df['Jawaban']))
print(input_ids)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


[[    3  3397  1675 ...     2     2     2]
 [    3  3397  1510 ...     2     2     2]
 [    3 10456  2485 ...     2     2     2]
 ...
 [    3  8345  1507 ...     2     2     2]
 [    3  3397 20987 ...     2     2     2]
 [    3  2656  2739 ...     2     2     2]] ['sebuah universitas negeri terkemuka', 'sebuah universitas negeri terkemuka', 'Universitas ini didirikan pada tahun 1957', 'Universitas ini didirikan pada tahun 1957', 'universitas negeri terkemuka yang terletak di Semarang, Jawa Tengah, Indonesia', 'universitas negeri terkemuka yang terletak di Semarang, Jawa Tengah, Indonesia', 'Undip telah tumbuh dan berkembang menjadi salah satu perguruan tinggi terkemuka', 'Undip telah tumbuh dan berkembang menjadi salah satu perguruan tinggi terkemuka', 'Jenderal Sudirman, yang memiliki nama lahir "Sudirman Djojonegoro."', 'dinamai sesuai dengan nama seorang pahlawan nasional Indonesia, Jenderal Sudirman', 'Jenderal Sudirman, yang memiliki nama lahir "Sudirman Djojonegoro."', 'sebuah un

In [ ]:
import numpy as np

def find_subarray_indexes(array, subarray):
    n = len(array)
    m = len(subarray)

    for i in range(n - m + 1):
        if np.array_equal(array[i:i+m], subarray):
            return i, i + m - 1

    return -1, -1  # Return -1, -1 jika subarray tidak ditemukan

dataset_y = []
# Contoh penggunaan
main_array = input_ids['input_ids'].numpy()
sub_array = list(df['Jawaban'])

for x in range(len(main_array)):
    konteks = main_array[x]
    answer = tokenizer(sub_array[x], return_tensors='tf',add_special_tokens=False)['input_ids'].numpy()[0]
    # print(konteks)
    # print(answer)
    start_index, end_index = find_subarray_indexes(konteks, answer)

    if start_index != -1:
        dataset_y.append([start_index, end_index])
        print(f"Subarray ditemukan dari indeks {start_index} hingga {end_index}.")
    else:
        dataset_y.append([0, 0])
        print("Subarray tidak ditemukan.")

print(dataset_y)

Subarray ditemukan dari indeks 18 hingga 21.
Subarray ditemukan dari indeks 18 hingga 21.
Subarray ditemukan dari indeks 31 hingga 36.
Subarray ditemukan dari indeks 31 hingga 36.
Subarray ditemukan dari indeks 23 hingga 34.
Subarray ditemukan dari indeks 18 hingga 29.
Subarray ditemukan dari indeks 63 hingga 74.
Subarray ditemukan dari indeks 68 hingga 79.
Subarray ditemukan dari indeks 51 hingga 63.
Subarray ditemukan dari indeks 45 hingga 55.
Subarray ditemukan dari indeks 49 hingga 61.
Subarray ditemukan dari indeks 16 hingga 19.
Subarray ditemukan dari indeks 6 hingga 19.
Subarray ditemukan dari indeks 8 hingga 21.
Subarray ditemukan dari indeks 15 hingga 25.
Subarray ditemukan dari indeks 15 hingga 25.
Subarray ditemukan dari indeks 66 hingga 87.
Subarray ditemukan dari indeks 64 hingga 69.
Subarray ditemukan dari indeks 120 hingga 128.
Subarray ditemukan dari indeks 27 hingga 30.
Subarray ditemukan dari indeks 43 hingga 56.
Subarray ditemukan dari indeks 91 hingga 104.
Subarray 

In [ ]:
indeks_00 = [index for index, item in enumerate(dataset_y) if item == [0, 0]]
dataset_y = [item for item in dataset_y if item != [0, 0]]
print(indeks_00)
print(dataset_y)

[26, 42, 43, 44, 45, 125, 126, 157, 158, 193, 194, 200, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 229, 230, 236, 243, 244, 246, 248, 250, 251, 252, 260, 261, 263, 264, 266, 267, 268]
[[18, 21], [18, 21], [31, 36], [31, 36], [23, 34], [18, 29], [63, 74], [68, 79], [51, 63], [45, 55], [49, 61], [16, 19], [6, 19], [8, 21], [15, 25], [15, 25], [66, 87], [64, 69], [120, 128], [27, 30], [43, 56], [91, 104], [114, 120], [67, 88], [56, 61], [43, 59], [102, 111], [65, 87], [54, 59], [9, 15], [38, 54], [63, 82], [116, 141], [62, 84], [60, 60], [31, 35], [9, 31], [33, 44], [60, 72], [81, 112], [113, 134], [7, 28], [11, 29], [67, 95], [41, 64], [12, 30], [12, 30], [7, 16], [80, 85], [92, 106], [42, 65], [39, 45], [24, 38], [21, 35], [50, 56], [72, 75], [9, 14], [17, 21], [48, 48], [46, 66], [54, 68], [7, 19], [30, 51], [57, 94], [17, 38], [102, 105], [114, 237], [10, 24], [40, 50], [153, 163], [234, 260], [284, 307], [356, 373], [7, 16], [85, 95], [133, 149], [15, 29], 

In [ ]:
for index_to_remove in indeks_00:
  df = df.drop(index_to_remove)

In [ ]:
input_ids = tokenizer(list(df['Pertanyaan']),list(df['Text']), return_tensors='tf', padding=True, truncation=True)
print(input_ids)

{'input_ids': <tf.Tensor: shape=(258, 506), dtype=int32, numpy=
array([[    3,  3397,  1675, ...,     2,     2,     2],
       [    3,  3397,  1510, ...,     2,     2,     2],
       [    3, 10456,  2485, ...,     2,     2,     2],
       ...,
       [    3,  8345,  1507, ...,     2,     2,     2],
       [    3,  3397, 20987, ...,     2,     2,     2],
       [    3,  2656,  2739, ...,     2,     2,     2]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(258, 506), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(258, 506), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32

In [ ]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy()
optimizer = tf.keras.optimizers.Adam(learning_rate=2e-8)

In [ ]:
def question_answering_loss(y_true, y_pred):
    print(y_true,y_pred)
    # Extract start_positions and end_positions from y_true
    start_positions = y_true[:, 0]  # Assuming the start_positions are in the first column
    end_positions = y_true[:, 1]    # Assuming the end_positions are in the second column

    # Extract start_logits and end_logits from y_pred
    start_logits = y_pred[:, :tf.shape(y_pred)[-1] // 2]
    end_logits = y_pred[:, tf.shape(y_pred)[-1] // 2:]
    print(start_logits,end_logits)

    start_positions_one_hot = tf.one_hot(start_positions, depth=tf.shape(start_logits)[-1])
    end_positions_one_hot = tf.one_hot(end_positions, depth=tf.shape(end_logits)[-1])

    start_loss = tf.keras.losses.categorical_crossentropy(start_positions_one_hot, start_logits, from_logits=True)
    end_loss = tf.keras.losses.categorical_crossentropy(end_positions_one_hot, end_logits, from_logits=True)

    # Sum both losses
    total_loss = start_loss + end_loss

    return total_loss

In [ ]:
model.save('/content/model_chatbot')

In [ ]:
loaded_model = tf.keras.models.load_model('/content/model_chatbot')

In [ ]:
def build_classifier_model():
    input_shape = (None,)
    input_ids = tf.keras.layers.Input(shape=input_shape, dtype=tf.int32, name='input_ids')
    token_type_ids = tf.keras.layers.Input(shape=input_shape, dtype=tf.int32, name='token_type_ids')
    attention_mask = tf.keras.layers.Input(shape=input_shape, dtype=tf.int32, name='attention_mask')
    output_neurons = input_shape[0]
    input_layer = {
        'attention_mask': attention_mask,
        'input_ids': input_ids,
        'token_type_ids': token_type_ids
    }

    # Mengambil output dari layer BERT
    output = loaded_model(input_layer)
    return tf.keras.Model(inputs=input_layer, outputs=output)

In [ ]:
model = build_classifier_model()
model.summary()

NameError: ignored

In [ ]:
def custom_accuracy_loss(y_true, y_pred):
    # Menghitung akurasi
    accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(y_true, axis=-1), tf.argmax(y_pred, axis=-1)), tf.float32))

    # Menghitung loss berdasarkan akurasi (1 - akurasi)
    loss = 1 - accuracy

    return loss

In [ ]:
model.compile(optimizer=optimizer, loss=question_answering_loss)

In [ ]:
import numpy as np

context = 'Universitas Hasanuddin (Unhas) adalah sebuah perguruan tinggi yang terletak di Makassar, Sulawesi Selatan, Indonesia. Didirikan pada tahun 1956, Unhas menjadi salah satu universitas terkemuka di Indonesia. Kampus ini menawarkan beragam program studi di tingkat sarjana, magister, dan doktor, melibatkan mahasiswa dalam berbagai bidang ilmu. Unhas dikenal karena komitmennya terhadap penelitian dan pengembangan, dengan fokus pada pembangunan berkelanjutan, keberlanjutan lingkungan, dan inovasi. Kampus ini memiliki fasilitas modern, termasuk laboratorium, perpustakaan, dan pusat penelitian yang mendukung aktivitas akademis dan riset. Dengan keberagaman budaya dan lingkungan yang mendukung, Unhas menciptakan suasana belajar yang dinamis dan inklusif. Perguruan tinggi ini juga berperan penting dalam menghasilkan lulusan yang siap bersaing di tingkat nasional maupun internasional.'
question = "kapan kampus Hasanuddin didirikan?"

inputs = tokenizer(question,context,return_tensors="tf")
answer = model.predict(dict(inputs))
start = int(tf.argmax(answer['start_logits'],axis=1))
end = int(tf.argmax(answer['end_logits'],axis=1))
print(start, end)
# print(list(inputs['input_ids']))
if end-start == 0:
  result = tf.reshape(inputs['input_ids'], [-1]).numpy()[start:end]
else:
  result = list(inputs['input_ids'])[0][start:end+2]

token_ids = result.numpy()

# Konversi token ke bentuk string
tokens = tokenizer.convert_ids_to_tokens(token_ids)
print(answer)
print(result)
# Gabungkan token menjadi teks
text = " ".join(tokens).replace(" ##", "")
# text_from_tokens = tokenizer.convert_tokens_to_string(result)
print(text)

1/1 [==============================] - 7s 7s/step
27 1
TFQuestionAnsweringModelOutput(loss=None, start_logits=array([[ -4.037068  ,   6.9867167 ,   3.101478  ,  -1.0669484 ,
          1.4422538 ,   0.8161534 ,  -5.3252673 ,   0.23918605,
         -6.365149  , -18.743774  ,  -6.2102294 , -20.550356  ,
        -21.17835   , -21.19977   , -15.887628  ,  -0.95731974,
        -14.344905  , -18.221449  , -17.56086   , -17.904343  ,
        -18.353643  , -19.312046  , -21.28551   , -22.079176  ,
        -18.477705  , -17.040682  ,   9.019375  ,  20.944569  ,
         10.395632  ,   7.735358  ,   3.8476877 , -10.261933  ,
         -3.8638997 , -21.016321  , -23.409882  , -22.805012  ,
        -23.097437  , -22.332703  , -23.856688  , -23.687454  ,
        -23.118374  ,  -4.647225  ,   5.9578233 , -11.137938  ,
        -20.969156  , -23.590488  , -23.353525  , -22.87078   ,
        -23.5826    , -23.936735  , -23.820532  , -23.82732   ,
        -23.978935  , -23.818417  , -23.953001  , -23.6710

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
class onthatlevel(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if logs.get('loss') < 0.08:
            self.model.stop_training = True

In [ ]:
model.save('/content/drive/MyDrive/chatbot1')

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint

# Path untuk menyimpan checkpoint pada setiap epoch
checkpoint_path_epoch = "/content/drive/MyDrive/chatbot_epoch.h5"

# Path untuk menyimpan checkpoint model terbaik
checkpoint_path_best = "/content/drive/MyDrive/chatbot_best.h5"

# Callback untuk menyimpan checkpoint pada setiap epoch
checkpoint_callback_epoch = ModelCheckpoint(
    filepath=checkpoint_path_epoch,
    save_weights_only=True,
    save_best_only=False,  # Set ke False agar menyimpan pada setiap epoch
    verbose=1
)

# Callback untuk menyimpan checkpoint model terbaik
checkpoint_callback_best = ModelCheckpoint(
    filepath=checkpoint_path_best,
    save_weights_only=True,
    save_best_only=True,  # Set ke True agar hanya menyimpan model terbaik
    monitor='loss',
    mode='min',
    verbose=1
)

In [ ]:
model.load_weights('/content/drive/MyDrive/chatbot_epoch.h5')

In [ ]:
model.fit(x=dict(input_ids), y=np.array(dataset_y),callbacks=[checkpoint_callback_epoch,checkpoint_callback_best],epochs=50,batch_size=4)

Epoch 1/50
Tensor("IteratorGetNext:3", shape=(None, 2), dtype=int64) Tensor("tf_bert_for_question_answering/Squeeze:0", shape=(None, 506), dtype=float32)
Tensor("question_answering_loss/strided_slice_3:0", shape=(None, 253), dtype=float32) Tensor("question_answering_loss/strided_slice_5:0", shape=(None, 253), dtype=float32)
Tensor("IteratorGetNext:3", shape=(None, 2), dtype=int64) Tensor("tf_bert_for_question_answering/Squeeze:0", shape=(None, 506), dtype=float32)
Tensor("question_answering_loss/strided_slice_3:0", shape=(None, 253), dtype=float32) Tensor("question_answering_loss/strided_slice_5:0", shape=(None, 253), dtype=float32)
65/65 [==============================] - ETA: 0s - loss: 0.0498
Epoch 1: saving model to /content/drive/MyDrive/chatbot_epoch.h5

Epoch 1: loss did not improve from 0.04878
65/65 [==============================] - 116s 638ms/step - loss: 0.0498
Epoch 2/50
65/65 [==============================] - ETA: 0s - loss: 0.0513
Epoch 2: saving model to /content/drive